// <auto-generated />
using FarmsteadMap.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmsteadMap.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103110210_Added constrain for incompatibilities")]
    partial class Addedconstrainforincompatibilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.Flower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GroundType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ground_type");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("flowers", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.Map", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_Private");

                    b.Property<string>("MapJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.Tree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.TreeIncompatibility", b =>
                {
                    b.Property<long>("Tree1Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tree1_id");

                    b.Property<long>("Tree2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("tree2_id");

                    b.HasKey("Tree1Id", "Tree2Id");

                    b.HasIndex("Tree2Id");

                    b.ToTable("trees_incompatibility", null, t =>
                        {
                            t.HasCheckConstraint("trees_incompatibility_check", "tree1_id < tree2_id");
                        });
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.TreeSort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GroundType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ground_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint")
                        .HasColumnName("tree_id");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.ToTable("tree_sorts", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_Active");

                    b.Property<bool>("IsSuperuser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_Superuser");

                    b.Property<string>("Lastname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.VegIncompatibility", b =>
                {
                    b.Property<long>("Veg1Id")
                        .HasColumnType("bigint")
                        .HasColumnName("veg1_id");

                    b.Property<long>("Veg2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("veg2_id");

                    b.HasKey("Veg1Id", "Veg2Id");

                    b.HasIndex("Veg2Id");

                    b.ToTable("veg_incompatibility", null, t =>
                        {
                            t.HasCheckConstraint("veg_incompatibility_check", "veg1_id < veg2_id");
                        });
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.VegSort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GroundType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ground_type");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("VegId")
                        .HasColumnType("bigint")
                        .HasColumnName("veg_id");

                    b.HasKey("Id");

                    b.HasIndex("VegId");

                    b.ToTable("veg_sorts", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.Vegetable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vegetables", (string)null);
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.Map", b =>
                {
                    b.HasOne("FarmsteadMap.DAL.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("map_user_fk");
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.TreeIncompatibility", b =>
                {
                    b.HasOne("FarmsteadMap.DAL.Data.Models.Tree", null)
                        .WithMany()
                        .HasForeignKey("Tree1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("incompatibility_tree1_fk");

                    b.HasOne("FarmsteadMap.DAL.Data.Models.Tree", null)
                        .WithMany()
                        .HasForeignKey("Tree2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("incompatibility_tree2_fk");
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.TreeSort", b =>
                {
                    b.HasOne("FarmsteadMap.DAL.Data.Models.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sorts_tree_fk");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.VegIncompatibility", b =>
                {
                    b.HasOne("FarmsteadMap.DAL.Data.Models.Vegetable", null)
                        .WithMany()
                        .HasForeignKey("Veg1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("incompatibility_veg1_fk");

                    b.HasOne("FarmsteadMap.DAL.Data.Models.Vegetable", null)
                        .WithMany()
                        .HasForeignKey("Veg2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("incompatibility_veg2_fk");
                });

            modelBuilder.Entity("FarmsteadMap.DAL.Data.Models.VegSort", b =>
                {
                    b.HasOne("FarmsteadMap.DAL.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sorts_veg_fk");

                    b.Navigation("Vegetable");
                });
#pragma warning restore 612, 618
        }
    }
}
